version: '3.1'

services:
  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: pontonovo
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
  adminer:
    image: adminer
    restart: "no"
    ports:
      - 9000:8080

volumes:
  my-db: